server:
  port: 8089
  max-http-header-size: 52428800
#  ssl:
#    key-store: 4637519_www.mrkleo.top.pfx
#    key-store-password: t17NhCxA
#    keyStoreType: PKCS12

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yundingxi.tell.mapper
  configuration:
    map-underscore-to-camel-case: true
#    开启执行sql日志打印###ll
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  #  profiles:
  #    active: @profileActive@
  datasource:
    #druid基本属性
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://8.136.1.98:3306/tell?serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useUnicode=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #druid相关配置
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      #配置初始化大小/最小/最大
      initial-size: 5
      min-idle: 1
      max-active: 50
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    hikari:
      connection-timeout: 5000
      max-lifetime: 60000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: 121.5.39.223
    port: 6379
    timeout: 300000
    password: 123
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-wait: 100000
        max-idle: 8
        min-idle: 0
  #自定义的监听的TOPIC路径
  message:
    topic-name: topic-test
  application:
    name: tell
time:
  cron: 0 0 12 * * ?